-- ============================================================
--        Customer Shopping Behavior Analysis
--        Database : customer
-- ============================================================


-- ============================================================
-- Q1. What is the total revenue generated by male vs. female customers?
-- ============================================================

SELECT
    gender,
    SUM(purchase_amount)                    AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;


-- ============================================================
-- Q2. Which customers used a discount but still spent more
--     than the average purchase amount?
-- ============================================================

SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;


-- ============================================================
-- Q3. Which are the top 5 products with the highest
--     average review rating?
-- ============================================================

SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2)            AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


-- ============================================================
-- Q4. Compare the average purchase amounts between
--     Standard and Express shipping.
-- ============================================================

SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2)          AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;


-- ============================================================
-- Q5. Do subscribed customers spend more?
--     Compare average spend and total revenue between
--     subscribers and non-subscribers.
-- ============================================================

SELECT
    subscription_status,
    COUNT(*)                                AS total_customers,
    ROUND(AVG(purchase_amount), 2)          AS avg_spend,
    ROUND(SUM(purchase_amount), 2)          AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend DESC;


-- ============================================================
-- Q6. Which 5 products have the highest percentage of
--     purchases with discounts applied?
-- ============================================================

SELECT
    item_purchased,
    COUNT(*)                                                        AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)      AS discounted_purchases,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*), 2
    )                                                               AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- ============================================================
-- Q7. Segment customers into New, Returning, and Loyal based
--     on their total number of previous purchases, and show
--     the count of each segment.
-- ============================================================

WITH segmented AS (
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases <= 5  THEN 'New'
            WHEN previous_purchases <= 20 THEN 'Returning'
            ELSE                               'Loyal'
        END                                 AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*)                                AS number_of_customers
FROM segmented
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


-- ============================================================
-- Q8. What are the top 3 most purchased products
--     within each category?
-- ============================================================

WITH ranked_products AS (
    SELECT
        category,
        item_purchased,
        COUNT(*)                            AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        )                                   AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM ranked_products
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- ============================================================
-- Q9. Are customers who are repeat buyers (more than 5
--     previous purchases) also likely to subscribe?
-- ============================================================

SELECT
    subscription_status,
    COUNT(*)                                AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;


-- ============================================================
-- Q10. What is the revenue contribution of each age group?
-- ============================================================

SELECT
    age_group,
    ROUND(SUM(purchase_amount), 2)          AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


